version: "3.8"

services:
  client:
    build:
      context: .
    container_name: Client
    command: python socket_client.py
    depends_on:
      - server
    networks:
      - interaction-network

  server:
    build:
      context: .
    container_name: Server
    command: python socket_server.py
    ports:
      - "5000:5000"
    networks:
      - interaction-network

networks:
  interaction-network: