version: "3.8"

services:
  producer:
    build:
      context: .
    container_name: Producer
    command: python producer.py
    depends_on:
      - consumer
    networks:
      - interaction-network

  consumer:
    build:
      context: .
    container_name: Consumer
    command: python consumer.py
    ports:
      - "5000:5000"
    networks:
      - interaction-network

networks:
  interaction-network: