version: "3.8"

services:
  socket_server:
    build:
      context: .
    container_name: socket_server
    command: python socket_server.py
    networks:
      - interaction-network

  socket_client:
    build:
      context: .
    container_name: socket_client
    command: python socket_client.py
    depends_on:
      - socket_server
    ports:
      - "5000:5000"
    networks:
      - interaction-network

networks:
  interaction-network:
